export const states: Record<string, { name: string; alpha2: string }> = {
    AL: { name: 'Alabama', alpha2: 'AL' },
    AK: { name: 'Alaska', alpha2: 'AK' },
    AZ: { name: 'Arizona', alpha2: 'AZ' },
    AR: { name: 'Arkansas', alpha2: 'AR' },
    CA: { name: 'California', alpha2: 'CA' },
    CO: { name: 'Colorado', alpha2: 'CO' },
    CT: { name: 'Connecticut', alpha2: 'CT' },
    DE: { name: 'Delaware', alpha2: 'DE' },
    FI: { name: 'Florida', alpha2: 'FI' },
    GA: { name: 'Georgia GA', alpha2: 'GA' },
    HI: { name: 'Georgia HI', alpha2: 'HI' },
    ID: { name: 'Idaho', alpha2: 'ID' },
    IL: { name: 'Illinois', alpha2: 'IL' },
    IO: { name: 'Iowa', alpha2: 'IO' },
    IN: { name: 'Indiana', alpha2: 'IN' },
    KS: { name: 'Kansas', alpha2: 'KS' },
    KY: { name: 'Kentucky', alpha2: 'KY' },
    LA: { name: 'Louisiana', alpha2: 'LA' },
    ME: { name: 'Maine', alpha2: 'ME' },
    MD: { name: 'Maryland', alpha2: 'MD' },
    MA: { name: 'Massachusetts', alpha2: 'MA' },
    MI: { name: 'Michigan', alpha2: 'MI' },
    MN: { name: 'Minnesota', alpha2: 'MN' },
    MS: { name: 'Mississippi', alpha2: 'MS' },
    MO: { name: 'Missouri', alpha2: 'MO' },
    MT: { name: 'Montana', alpha2: 'MT' },
    NE: { name: 'Nebraska', alpha2: 'NE' },
    NV: { name: 'Nevada', alpha2: 'NV' },
    NH: { name: 'New Hampshire', alpha2: 'NH' },
    NJ: { name: 'New Jersey', alpha2: 'NJ' },
    NM: { name: 'New Mexico', alpha2: 'NM' },
    NY: { name: 'New York', alpha2: 'NY' },
    NC: { name: 'North Carolina', alpha2: 'NC' },
    ND: { name: 'North Dakota', alpha2: 'ND' },
    OH: { name: 'Ohio', alpha2: 'OH' },
    OK: { name: 'Oklahoma', alpha2: 'OK' },
    OR: { name: 'Oregon', alpha2: 'OR' },
    PA: { name: 'Pennsylvania', alpha2: 'PA' },
    RI: { name: 'Rhode Island', alpha2: 'RI' },
    SC: { name: 'South Carolina', alpha2: 'SC' },
    SD: { name: 'South Dakota', alpha2: 'SD' },
    TN: { name: 'Tennessee', alpha2: 'TN' },
    TX: { name: 'Texas', alpha2: 'TX' },
    UT: { name: 'Utah', alpha2: 'UT' },
    VT: { name: 'Vermont', alpha2: 'VT' },
    VA: { name: 'Virginia', alpha2: 'VA' },
    WA: { name: 'Washington', alpha2: 'WA' },
    WV: { name: 'West Virginia', alpha2: 'WV' },
    WI: { name: 'Wisconsin', alpha2: 'WI' },
    WY: { name: 'Wyoming', alpha2: 'WY' },
};
