import { useMemo, useState } from 'react';
import { AppDropdownSelectField, AppDropdownSelectFieldProps, FilterGroup } from '../../components/inputs';

export interface Country {
    name: string;
    alpha2: string;
    alpha3: string;
    subregion: string;
    currencyCode: string;
}

interface CountryByName extends Country {
    id: number;
}

export const countriesWithUnduplicatedCodes: Record<string, Country> = {
    AF: {
        name: 'Afghanistan',
        alpha2: 'AF',
        alpha3: 'AFG',
        subregion: 'Southern Asia',
        currencyCode: 'AFN',
    },
    AX: {
        name: 'Åland Islands',
        alpha2: 'AX',
        alpha3: 'ALA',
        subregion: 'Northern Europe',
        currencyCode: 'EUR',
    },
    AL: {
        name: 'Albania',
        alpha2: 'AL',
        alpha3: 'ALB',
        subregion: 'Southern Europe',
        currencyCode: 'ALL',
    },
    DZ: {
        name: 'Algeria',
        alpha2: 'DZ',
        alpha3: 'DZA',
        subregion: 'Northern Africa',
        currencyCode: 'DZD',
    },
    AS: {
        name: 'American Samoa',
        alpha2: 'AS',
        alpha3: 'ASM',
        subregion: 'Polynesia',
        currencyCode: 'USD',
    },
    AD: {
        name: 'Andorra',
        alpha2: 'AD',
        alpha3: 'AND',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    AO: {
        name: 'Angola',
        alpha2: 'AO',
        alpha3: 'AGO',
        subregion: 'Middle Africa',
        currencyCode: 'AOA',
    },
    AI: {
        name: 'Anguilla',
        alpha2: 'AI',
        alpha3: 'AIA',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    AQ: {
        name: 'Antarctica',
        alpha2: 'AQ',
        alpha3: 'ATA',
        subregion: 'Other',
        currencyCode: 'AQD',
    },
    AG: {
        name: 'Antigua and Barbuda',
        alpha2: 'AG',
        alpha3: 'ATG',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    AR: {
        name: 'Argentina',
        alpha2: 'AR',
        alpha3: 'ARG',
        subregion: 'South America',
        currencyCode: 'ARS',
    },
    AM: {
        name: 'Armenia',
        alpha2: 'AM',
        alpha3: 'ARM',
        subregion: 'Western Asia',
        currencyCode: 'AMD',
    },
    AW: {
        name: 'Aruba',
        alpha2: 'AW',
        alpha3: 'ABW',
        subregion: 'Caribbean',
        currencyCode: 'ANG',
    },
    AU: {
        name: 'Australia',
        alpha2: 'AU',
        alpha3: 'AUS',
        subregion: 'Australia and New Zealand',
        currencyCode: 'AUD',
    },
    AT: {
        name: 'Austria',
        alpha2: 'AT',
        alpha3: 'AUT',
        subregion: 'Western Europe',
        currencyCode: 'EUR',
    },
    AZ: {
        name: 'Azerbaijan',
        alpha2: 'AZ',
        alpha3: 'AZE',
        subregion: 'Western Asia',
        currencyCode: 'AZN',
    },
    BS: {
        name: 'Bahamas',
        alpha2: 'BS',
        alpha3: 'BHS',
        subregion: 'Caribbean',
        currencyCode: 'BSD',
    },
    BH: {
        name: 'Bahrain',
        alpha2: 'BH',
        alpha3: 'BHR',
        subregion: 'Western Asia',
        currencyCode: 'BHD',
    },
    BD: {
        name: 'Bangladesh',
        alpha2: 'BD',
        alpha3: 'BGD',
        subregion: 'Southern Asia',
        currencyCode: 'BDT',
    },
    BB: {
        name: 'Barbados',
        alpha2: 'BB',
        alpha3: 'BRB',
        subregion: 'Caribbean',
        currencyCode: 'BBD',
    },
    BY: {
        name: 'Belarus',
        alpha2: 'BY',
        alpha3: 'BLR',
        subregion: 'Eastern Europe',
        currencyCode: 'BYN',
    },
    BE: {
        name: 'Belgium',
        alpha2: 'BE',
        alpha3: 'BEL',
        subregion: 'Western Europe',
        currencyCode: 'EUR',
    },
    BZ: {
        name: 'Belize',
        alpha2: 'BZ',
        alpha3: 'BLZ',
        subregion: 'Central America',
        currencyCode: 'BZD',
    },
    BJ: {
        name: 'Benin',
        alpha2: 'BJ',
        alpha3: 'BEN',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    BM: {
        name: 'Bermuda',
        alpha2: 'BM',
        alpha3: 'BMU',
        subregion: 'Northern America',
        currencyCode: 'BMD',
    },
    BT: {
        name: 'Bhutan',
        alpha2: 'BT',
        alpha3: 'BTN',
        subregion: 'Southern Asia',
        currencyCode: 'BTN',
    },
    BO: {
        name: 'Bolivia (Plurinational State of)',
        alpha2: 'BO',
        alpha3: 'BOL',
        subregion: 'South America',
        currencyCode: 'BOB',
    },
    BQ: {
        name: 'Bonaire, Sint Eustatius and Saba',
        alpha2: 'BQ',
        alpha3: 'BES',
        subregion: 'Caribbean',
        currencyCode: 'ANG',
    },
    BA: {
        name: 'Bosnia and Herzegovina',
        alpha2: 'BA',
        alpha3: 'BIH',
        subregion: 'Southern Europe',
        currencyCode: 'BAM',
    },
    BW: {
        name: 'Botswana',
        alpha2: 'BW',
        alpha3: 'BWA',
        subregion: 'Southern Africa',
        currencyCode: 'BWP',
    },
    BV: {
        name: 'Bouvet Island',
        alpha2: 'BV',
        alpha3: 'BVT',
        subregion: 'Other',
        currencyCode: 'NOK',
    },
    BR: {
        name: 'Brazil',
        alpha2: 'BR',
        alpha3: 'BRA',
        subregion: 'South America',
        currencyCode: 'BRL',
    },
    IO: {
        name: 'British Indian Ocean Territory',
        alpha2: 'IO',
        alpha3: 'IOT',
        subregion: 'Eastern Africa',
        currencyCode: 'USD',
    },
    BN: {
        name: 'Brunei Darussalam',
        alpha2: 'BN',
        alpha3: 'BRN',
        subregion: 'South-Eastern Asia',
        currencyCode: 'BND',
    },
    BG: {
        name: 'Bulgaria',
        alpha2: 'BG',
        alpha3: 'BGR',
        subregion: 'Eastern Europe',
        currencyCode: 'BGN',
    },
    BF: {
        name: 'Burkina Faso',
        alpha2: 'BF',
        alpha3: 'BFA',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    CV: {
        name: 'Cabo Verde',
        alpha2: 'CV',
        alpha3: 'CPV',
        subregion: 'Western Africa',
        currencyCode: 'CVE',
    },
    BI: {
        name: 'Burundi',
        alpha2: 'BI',
        alpha3: 'BDI',
        subregion: 'Eastern Africa',
        currencyCode: 'BIF',
    },
    KH: {
        name: 'Cambodia',
        alpha2: 'KH',
        alpha3: 'KHM',
        subregion: 'South-Eastern Asia',
        currencyCode: 'KHR',
    },
    CM: {
        name: 'Cameroon',
        alpha2: 'CM',
        alpha3: 'CMR',
        subregion: 'Middle Africa',
        currencyCode: 'XAF',
    },
    CA: {
        name: 'Canada',
        alpha2: 'CA',
        alpha3: 'CAN',
        subregion: 'Northern America',
        currencyCode: 'CAD',
    },
    KY: {
        name: 'Cayman Islands',
        alpha2: 'KY',
        alpha3: 'CYM',
        subregion: 'Caribbean',
        currencyCode: 'KYD',
    },
    CF: {
        name: 'Central African Republic',
        alpha2: 'CF',
        alpha3: 'CAF',
        subregion: 'Middle Africa',
        currencyCode: 'XAF',
    },
    TD: {
        name: 'Chad',
        alpha2: 'TD',
        alpha3: 'TCD',
        subregion: 'Middle Africa',
        currencyCode: 'XAF',
    },
    CL: {
        name: 'Chile',
        alpha2: 'CL',
        alpha3: 'CHL',
        subregion: 'South America',
        currencyCode: 'CLP',
    },
    CN: {
        name: 'China',
        alpha2: 'CN',
        alpha3: 'CHN',
        subregion: 'Eastern Asia',
        currencyCode: 'CNY',
    },
    CR: {
        name: 'Costa Rica',
        alpha2: 'CR',
        alpha3: 'CRI',
        subregion: 'Central America',
        currencyCode: 'CRC',
    },
    CU: {
        name: 'Cuba',
        alpha2: 'CU',
        alpha3: 'CUB',
        subregion: 'Caribbean',
        currencyCode: 'CUP',
    },
    CI: {
        name: "Côte d'Ivoire",
        alpha2: 'CI',
        alpha3: 'CIV',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    HR: {
        name: 'Croatia',
        alpha2: 'HR',
        alpha3: 'HRV',
        subregion: 'Southern Europe',
        currencyCode: 'HRK',
    },
    CW: {
        name: 'Curaçao',
        alpha2: 'CW',
        alpha3: 'CUW',
        subregion: 'Caribbean',
        currencyCode: 'ANG',
    },
    CY: {
        name: 'Cyprus',
        alpha2: 'CY',
        alpha3: 'CYP',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    CZ: {
        name: 'Czechia',
        alpha2: 'CZ',
        alpha3: 'CZE',
        subregion: 'Eastern Europe',
        currencyCode: 'CZK',
    },
    DK: {
        name: 'Denmark',
        alpha2: 'DK',
        alpha3: 'DNK',
        subregion: 'Northern Europe',
        currencyCode: 'DKK',
    },
    DJ: {
        name: 'Djibouti',
        alpha2: 'DJ',
        alpha3: 'DJI',
        subregion: 'Eastern Africa',
        currencyCode: 'DJF',
    },
    DM: {
        name: 'Dominica',
        alpha2: 'DM',
        alpha3: 'DMA',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    DO: {
        name: 'Dominican Republic',
        alpha2: 'DO',
        alpha3: 'DOM',
        subregion: 'Caribbean',
        currencyCode: 'DOP',
    },
    CX: {
        name: 'Christmas Island',
        alpha2: 'CX',
        alpha3: 'CXR',
        subregion: 'Australia and New Zealand',
        currencyCode: 'AUD',
    },
    CC: {
        name: 'Cocos (Keeling) Islands',
        alpha2: 'CC',
        alpha3: 'CCK',
        subregion: 'Australia and New Zealand',
        currencyCode: 'AUD',
    },
    CO: {
        name: 'Colombia',
        alpha2: 'CO',
        alpha3: 'COL',
        subregion: 'South America',
        currencyCode: 'COP',
    },
    KM: {
        name: 'Comoros',
        alpha2: 'KM',
        alpha3: 'COM',
        subregion: 'Eastern Africa',
        currencyCode: 'KMF',
    },
    CG: {
        name: 'Congo',
        alpha2: 'CG',
        alpha3: 'COG',
        subregion: 'Middle Africa',
        currencyCode: 'XAF',
    },
    CD: {
        name: 'Congo, Democratic Republic of the',
        alpha2: 'CD',
        alpha3: 'COD',
        subregion: 'Middle Africa',
        currencyCode: 'CDF',
    },
    CK: {
        name: 'Cook Islands',
        alpha2: 'CK',
        alpha3: 'COK',
        subregion: 'Polynesia',
        currencyCode: 'NZD',
    },
    EC: {
        name: 'Ecuador',
        alpha2: 'EC',
        alpha3: 'ECU',
        subregion: 'South America',
        currencyCode: 'USD',
    },
    EG: {
        name: 'Egypt',
        alpha2: 'EG',
        alpha3: 'EGY',
        subregion: 'Northern Africa',
        currencyCode: 'EGP',
    },
    SV: {
        name: 'El Salvador',
        alpha2: 'SV',
        alpha3: 'SLV',
        subregion: 'Central America',
        currencyCode: 'USD',
    },
    GQ: {
        name: 'Equatorial Guinea',
        alpha2: 'GQ',
        alpha3: 'GNQ',
        subregion: 'Middle Africa',
        currencyCode: 'XAF',
    },
    ER: {
        name: 'Eritrea',
        alpha2: 'ER',
        alpha3: 'ERI',
        subregion: 'Eastern Africa',
        currencyCode: 'ERN',
    },
    EE: {
        name: 'Estonia',
        alpha2: 'EE',
        alpha3: 'EST',
        subregion: 'Northern Europe',
        currencyCode: 'EUR',
    },
    SZ: {
        name: 'Eswatini',
        alpha2: 'SZ',
        alpha3: 'SWZ',
        subregion: 'Southern Africa',
        currencyCode: 'SZL',
    },
    ET: {
        name: 'Ethiopia',
        alpha2: 'ET',
        alpha3: 'ETH',
        subregion: 'Eastern Africa',
        currencyCode: 'ETB',
    },
    FK: {
        name: 'Falkland Islands (Malvinas)',
        alpha2: 'FK',
        alpha3: 'FLK',
        subregion: 'South America',
        currencyCode: 'FKP',
    },
    FO: {
        name: 'Faroe Islands',
        alpha2: 'FO',
        alpha3: 'FRO',
        subregion: 'Northern Europe',
        currencyCode: 'DKK',
    },
    FJ: {
        name: 'Fiji',
        alpha2: 'FJ',
        alpha3: 'FJI',
        subregion: 'Melanesia',
        currencyCode: 'FJD',
    },
    FI: {
        name: 'Finland',
        alpha2: 'FI',
        alpha3: 'FIN',
        subregion: 'Northern Europe',
        currencyCode: 'EUR',
    },
    FR: {
        name: 'France',
        alpha2: 'FR',
        alpha3: 'FRA',
        subregion: 'Western Europe',
        currencyCode: 'EUR',
    },
    GF: {
        name: 'French Guiana',
        alpha2: 'GF',
        alpha3: 'GUF',
        subregion: 'South America',
        currencyCode: 'EUR',
    },
    PF: {
        name: 'French Polynesia',
        alpha2: 'PF',
        alpha3: 'PYF',
        subregion: 'Polynesia',
        currencyCode: 'XPF',
    },
    TF: {
        name: 'French Southern Territories',
        alpha2: 'TF',
        alpha3: 'ATF',
        subregion: 'Southern Africa',
        currencyCode: 'EUR',
    },
    GA: {
        name: 'Gabon',
        alpha2: 'GA',
        alpha3: 'GAB',
        subregion: 'Middle Africa',
        currencyCode: 'XAF',
    },
    GM: {
        name: 'Gambia',
        alpha2: 'GM',
        alpha3: 'GMB',
        subregion: 'Western Africa',
        currencyCode: 'GMD',
    },
    GE: {
        name: 'Georgia',
        alpha2: 'GE',
        alpha3: 'GEO',
        subregion: 'Western Asia',
        currencyCode: 'GEL',
    },
    DE: {
        name: 'Germany',
        alpha2: 'DE',
        alpha3: 'DEU',
        subregion: 'Western Europe',
        currencyCode: 'EUR',
    },
    GH: {
        name: 'Ghana',
        alpha2: 'GH',
        alpha3: 'GHA',
        subregion: 'Western Africa',
        currencyCode: 'GHS',
    },
    GI: {
        name: 'Gibraltar',
        alpha2: 'GI',
        alpha3: 'GIB',
        subregion: 'Southern Europe',
        currencyCode: 'GIP',
    },
    GR: {
        name: 'Greece',
        alpha2: 'GR',
        alpha3: 'GRC',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    GL: {
        name: 'Greenland',
        alpha2: 'GL',
        alpha3: 'GRL',
        subregion: 'Northern America',
        currencyCode: 'DKK',
    },
    GD: {
        name: 'Grenada',
        alpha2: 'GD',
        alpha3: 'GRD',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    GP: {
        name: 'Guadeloupe',
        alpha2: 'GP',
        alpha3: 'GLP',
        subregion: 'Caribbean',
        currencyCode: 'EUR',
    },
    GU: {
        name: 'Guam',
        alpha2: 'GU',
        alpha3: 'GUM',
        subregion: 'Micronesia',
        currencyCode: 'USD',
    },
    GT: {
        name: 'Guatemala',
        alpha2: 'GT',
        alpha3: 'GTM',
        subregion: 'Central America',
        currencyCode: 'GTQ',
    },
    GG: {
        name: 'Guernsey',
        alpha2: 'GG',
        alpha3: 'GGY',
        subregion: 'Northern Europe',
        currencyCode: 'GGP',
    },
    GN: {
        name: 'Guinea',
        alpha2: 'GN',
        alpha3: 'GIN',
        subregion: 'Western Africa',
        currencyCode: 'GNF',
    },
    GW: {
        name: 'Guinea-Bissau',
        alpha2: 'GW',
        alpha3: 'GNB',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    GY: {
        name: 'Guyana',
        alpha2: 'GY',
        alpha3: 'GUY',
        subregion: 'South America',
        currencyCode: 'GYD',
    },
    HT: {
        name: 'Haiti',
        alpha2: 'HT',
        alpha3: 'HTI',
        subregion: 'Caribbean',
        currencyCode: 'HTG',
    },
    HM: {
        name: 'Heard Island and McDonald Islands',
        alpha2: 'HM',
        alpha3: 'HMD',
        subregion: 'Other',
        currencyCode: 'AUD',
    },
    VA: {
        name: 'Holy See',
        alpha2: 'VA',
        alpha3: 'VAT',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    HN: {
        name: 'Honduras',
        alpha2: 'HN',
        alpha3: 'HND',
        subregion: 'Central America',
        currencyCode: 'HNL',
    },
    HK: {
        name: 'Hong Kong',
        alpha2: 'HK',
        alpha3: 'HKG',
        subregion: 'Eastern Asia',
        currencyCode: 'HKD',
    },
    HU: {
        name: 'Hungary',
        alpha2: 'HU',
        alpha3: 'HUN',
        subregion: 'Eastern Europe',
        currencyCode: 'HUF',
    },
    IS: {
        name: 'Iceland',
        alpha2: 'IS',
        alpha3: 'ISL',
        subregion: 'Northern Europe',
        currencyCode: 'ISK',
    },
    IN: {
        name: 'India',
        alpha2: 'IN',
        alpha3: 'IND',
        subregion: 'Southern Asia',
        currencyCode: 'INR',
    },
    ID: {
        name: 'Indonesia',
        alpha2: 'ID',
        alpha3: 'IDN',
        subregion: 'South-Eastern Asia',
        currencyCode: 'IDR',
    },
    IQ: {
        name: 'Iraq',
        alpha2: 'IQ',
        alpha3: 'IRQ',
        subregion: 'Western Asia',
        currencyCode: 'IQD',
    },
    IR: {
        name: 'Iran (Islamic Republic of)',
        alpha2: 'IR',
        alpha3: 'IRN',
        subregion: 'Southern Asia',
        currencyCode: 'IRR',
    },
    IE: {
        name: 'Ireland',
        alpha2: 'IE',
        alpha3: 'IRL',
        subregion: 'Northern Europe',
        currencyCode: 'EUR',
    },
    IM: {
        name: 'Isle of Man',
        alpha2: 'IM',
        alpha3: 'IMN',
        subregion: 'Northern Europe',
        currencyCode: 'GBP',
    },
    IL: {
        name: 'Israel',
        alpha2: 'IL',
        alpha3: 'ISR',
        subregion: 'Western Asia',
        currencyCode: 'ILS',
    },
    IT: {
        name: 'Italy',
        alpha2: 'IT',
        alpha3: 'ITA',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    JM: {
        name: 'Jamaica',
        alpha2: 'JM',
        alpha3: 'JAM',
        subregion: 'Caribbean',
        currencyCode: 'JMD',
    },
    JP: {
        name: 'Japan',
        alpha2: 'JP',
        alpha3: 'JPN',
        subregion: 'Eastern Asia',
        currencyCode: 'JPY',
    },
    JE: {
        name: 'Jersey',
        alpha2: 'JE',
        alpha3: 'JEY',
        subregion: 'Northern Europe',
        currencyCode: 'GBP',
    },
    JO: {
        name: 'Jordan',
        alpha2: 'JO',
        alpha3: 'JOR',
        subregion: 'Western Asia',
        currencyCode: 'JOD',
    },
    KZ: {
        name: 'Kazakhstan',
        alpha2: 'KZ',
        alpha3: 'KAZ',
        subregion: 'Central Asia',
        currencyCode: 'KZT',
    },
    KE: {
        name: 'Kenya',
        alpha2: 'KE',
        alpha3: 'KEN',
        subregion: 'Eastern Africa',
        currencyCode: 'KES',
    },
    KI: {
        name: 'Kiribati',
        alpha2: 'KI',
        alpha3: 'KIR',
        subregion: 'Micronesia',
        currencyCode: 'AUD',
    },
    KP: {
        name: "Korea (Democratic People's Republic of)",
        alpha2: 'KP',
        alpha3: 'PRK',
        subregion: 'Eastern Asia',
        currencyCode: 'KPW',
    },
    KR: {
        name: 'Korea, Republic of',
        alpha2: 'KR',
        alpha3: 'KOR',
        subregion: 'Eastern Asia',
        currencyCode: 'KRW',
    },
    KW: {
        name: 'Kuwait',
        alpha2: 'KW',
        alpha3: 'KWT',
        subregion: 'Western Asia',
        currencyCode: 'KWD',
    },
    KG: {
        name: 'Kyrgyzstan',
        alpha2: 'KG',
        alpha3: 'KGZ',
        subregion: 'Central Asia',
        currencyCode: 'KGS',
    },
    LA: {
        name: "Lao People's Democratic Republic",
        alpha2: 'LA',
        alpha3: 'LAO',
        subregion: 'South-Eastern Asia',
        currencyCode: 'LAK',
    },
    LV: {
        name: 'Latvia',
        alpha2: 'LV',
        alpha3: 'LVA',
        subregion: 'Northern Europe',
        currencyCode: 'EUR',
    },
    LB: {
        name: 'Lebanon',
        alpha2: 'LB',
        alpha3: 'LBN',
        subregion: 'Western Asia',
        currencyCode: 'LBP',
    },
    LS: {
        name: 'Lesotho',
        alpha2: 'LS',
        alpha3: 'LSO',
        subregion: 'Southern Africa',
        currencyCode: 'LSL',
    },
    LR: {
        name: 'Liberia',
        alpha2: 'LR',
        alpha3: 'LBR',
        subregion: 'Western Africa',
        currencyCode: 'LRD',
    },
    LY: {
        name: 'Libya',
        alpha2: 'LY',
        alpha3: 'LBY',
        subregion: 'Northern Africa',
        currencyCode: 'LYD',
    },
    LI: {
        name: 'Liechtenstein',
        alpha2: 'LI',
        alpha3: 'LIE',
        subregion: 'Western Europe',
        currencyCode: 'CHF',
    },
    LT: {
        name: 'Lithuania',
        alpha2: 'LT',
        alpha3: 'LTU',
        subregion: 'Northern Europe',
        currencyCode: 'EUR',
    },
    LU: {
        name: 'Luxembourg',
        alpha2: 'LU',
        alpha3: 'LUX',
        subregion: 'Western Europe',
        currencyCode: 'EUR',
    },
    MO: {
        name: 'Macao',
        alpha2: 'MO',
        alpha3: 'MAC',
        subregion: 'Eastern Asia',
        currencyCode: 'MOP',
    },
    MG: {
        name: 'Madagascar',
        alpha2: 'MG',
        alpha3: 'MDG',
        subregion: 'Eastern Africa',
        currencyCode: 'MGA',
    },
    MW: {
        name: 'Malawi',
        alpha2: 'MW',
        alpha3: 'MWI',
        subregion: 'Eastern Africa',
        currencyCode: 'MWK',
    },
    MY: {
        name: 'Malaysia',
        alpha2: 'MY',
        alpha3: 'MYS',
        subregion: 'South-Eastern Asia',
        currencyCode: 'MYR',
    },
    MV: {
        name: 'Maldives',
        alpha2: 'MV',
        alpha3: 'MDV',
        subregion: 'Southern Asia',
        currencyCode: 'MVR',
    },
    ML: {
        name: 'Mali',
        alpha2: 'ML',
        alpha3: 'MLI',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    MT: {
        name: 'Malta',
        alpha2: 'MT',
        alpha3: 'MLT',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    MH: {
        name: 'Marshall Islands',
        alpha2: 'MH',
        alpha3: 'MHL',
        subregion: 'Micronesia',
        currencyCode: 'USD',
    },
    MQ: {
        name: 'Martinique',
        alpha2: 'MQ',
        alpha3: 'MTQ',
        subregion: 'Caribbean',
        currencyCode: 'EUR',
    },
    MR: {
        name: 'Mauritania',
        alpha2: 'MR',
        alpha3: 'MRT',
        subregion: 'Western Africa',
        currencyCode: 'MRO',
    },
    MU: {
        name: 'Mauritius',
        alpha2: 'MU',
        alpha3: 'MUS',
        subregion: 'Eastern Africa',
        currencyCode: 'MUR',
    },
    YT: {
        name: 'Mayotte',
        alpha2: 'YT',
        alpha3: 'MYT',
        subregion: 'Eastern Africa',
        currencyCode: 'EUR',
    },
    MX: {
        name: 'Mexico',
        alpha2: 'MX',
        alpha3: 'MEX',
        subregion: 'Central America',
        currencyCode: 'MXN',
    },
    FM: {
        name: 'Micronesia (Federated States of)',
        alpha2: 'FM',
        alpha3: 'FSM',
        subregion: 'Micronesia',
        currencyCode: 'USD',
    },
    MD: {
        name: 'Moldova, Republic of',
        alpha2: 'MD',
        alpha3: 'MDA',
        subregion: 'Eastern Europe',
        currencyCode: 'MDL',
    },
    MC: {
        name: 'Monaco',
        alpha2: 'MC',
        alpha3: 'MCO',
        subregion: 'Western Europe',
        currencyCode: 'EUR',
    },
    MN: {
        name: 'Mongolia',
        alpha2: 'MN',
        alpha3: 'MNG',
        subregion: 'Eastern Asia',
        currencyCode: 'MNT',
    },
    ME: {
        name: 'Montenegro',
        alpha2: 'ME',
        alpha3: 'MNE',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    MS: {
        name: 'Montserrat',
        alpha2: 'MS',
        alpha3: 'MSR',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    MA: {
        name: 'Morocco',
        alpha2: 'MA',
        alpha3: 'MAR',
        subregion: 'Northern Africa',
        currencyCode: 'MAD',
    },
    MZ: {
        name: 'Mozambique',
        alpha2: 'MZ',
        alpha3: 'MOZ',
        subregion: 'Eastern Africa',
        currencyCode: 'MZN',
    },
    MM: {
        name: 'Myanmar',
        alpha2: 'MM',
        alpha3: 'MMR',
        subregion: 'South-Eastern Asia',
        currencyCode: 'MMK',
    },
    NA: {
        name: 'Namibia',
        alpha2: 'NA',
        alpha3: 'NAM',
        subregion: 'Southern Africa',
        currencyCode: 'NAD',
    },
    NR: {
        name: 'Nauru',
        alpha2: 'NR',
        alpha3: 'NRU',
        subregion: 'Micronesia',
        currencyCode: 'AUD',
    },
    NP: {
        name: 'Nepal',
        alpha2: 'NP',
        alpha3: 'NPL',
        subregion: 'Southern Asia',
        currencyCode: 'NPR',
    },
    NL: {
        name: 'Netherlands',
        alpha2: 'NL',
        alpha3: 'NLD',
        subregion: 'Western Europe',
        currencyCode: 'EUR',
    },
    NC: {
        name: 'New Caledonia',
        alpha2: 'NC',
        alpha3: 'NCL',
        subregion: 'Melanesia',
        currencyCode: 'XPF',
    },
    NZ: {
        name: 'New Zealand',
        alpha2: 'NZ',
        alpha3: 'NZL',
        subregion: 'Australia and New Zealand',
        currencyCode: 'NZD',
    },
    NI: {
        name: 'Nicaragua',
        alpha2: 'NI',
        alpha3: 'NIC',
        subregion: 'Central America',
        currencyCode: 'NIO',
    },
    NE: {
        name: 'Niger',
        alpha2: 'NE',
        alpha3: 'NER',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    NG: {
        name: 'Nigeria',
        alpha2: 'NG',
        alpha3: 'NGA',
        subregion: 'Western Africa',
        currencyCode: 'NGN',
    },
    NU: {
        name: 'Niue',
        alpha2: 'NU',
        alpha3: 'NIU',
        subregion: 'Polynesia',
        currencyCode: 'NZD',
    },
    NF: {
        name: 'Norfolk Island',
        alpha2: 'NF',
        alpha3: 'NFK',
        subregion: 'Australia and New Zealand',
        currencyCode: 'AUD',
    },
    MK: {
        name: 'North Macedonia',
        alpha2: 'MK',
        alpha3: 'MKD',
        subregion: 'Southern Europe',
        currencyCode: 'MKD',
    },
    MP: {
        name: 'Northern Mariana Islands',
        alpha2: 'MP',
        alpha3: 'MNP',
        subregion: 'Micronesia',
        currencyCode: 'USD',
    },
    NO: {
        name: 'Norway',
        alpha2: 'NO',
        alpha3: 'NOR',
        subregion: 'Northern Europe',
        currencyCode: 'NOK',
    },
    OM: {
        name: 'Oman',
        alpha2: 'OM',
        alpha3: 'OMN',
        subregion: 'Western Asia',
        currencyCode: 'OMR',
    },
    PK: {
        name: 'Pakistan',
        alpha2: 'PK',
        alpha3: 'PAK',
        subregion: 'Southern Asia',
        currencyCode: 'PKR',
    },
    PW: {
        name: 'Palau',
        alpha2: 'PW',
        alpha3: 'PLW',
        subregion: 'Micronesia',
        currencyCode: 'USD',
    },
    PS: {
        name: 'Palestine, State of',
        alpha2: 'PS',
        alpha3: 'PSE',
        subregion: 'Western Asia',
        currencyCode: 'JOD',
    },
    PA: {
        name: 'Panama',
        alpha2: 'PA',
        alpha3: 'PAN',
        subregion: 'Central America',
        currencyCode: 'PAB',
    },
    PG: {
        name: 'Papua New Guinea',
        alpha2: 'PG',
        alpha3: 'PNG',
        subregion: 'Melanesia',
        currencyCode: 'PGK',
    },
    PY: {
        name: 'Paraguay',
        alpha2: 'PY',
        alpha3: 'PRY',
        subregion: 'South America',
        currencyCode: 'PYG',
    },
    PE: {
        name: 'Peru',
        alpha2: 'PE',
        alpha3: 'PER',
        subregion: 'South America',
        currencyCode: 'PEN',
    },
    PH: {
        name: 'Philippines',
        alpha2: 'PH',
        alpha3: 'PHL',
        subregion: 'South-Eastern Asia',
        currencyCode: 'PHP',
    },
    PN: {
        name: 'Pitcairn',
        alpha2: 'PN',
        alpha3: 'PCN',
        subregion: 'Polynesia',
        currencyCode: 'NZD',
    },
    PL: {
        name: 'Poland',
        alpha2: 'PL',
        alpha3: 'POL',
        subregion: 'Eastern Europe',
        currencyCode: 'PLN',
    },
    PT: {
        name: 'Portugal',
        alpha2: 'PT',
        alpha3: 'PRT',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    PR: {
        name: 'Puerto Rico',
        alpha2: 'PR',
        alpha3: 'PRI',
        subregion: 'Caribbean',
        currencyCode: 'USD',
    },
    QA: {
        name: 'Qatar',
        alpha2: 'QA',
        alpha3: 'QAT',
        subregion: 'Western Asia',
        currencyCode: 'QAR',
    },
    RE: {
        name: 'Réunion',
        alpha2: 'RE',
        alpha3: 'REU',
        subregion: 'Eastern Africa',
        currencyCode: 'EUR',
    },
    RO: {
        name: 'Romania',
        alpha2: 'RO',
        alpha3: 'ROU',
        subregion: 'Eastern Europe',
        currencyCode: 'RON',
    },
    RU: {
        name: 'Russian Federation',
        alpha2: 'RU',
        alpha3: 'RUS',
        subregion: 'Eastern Europe',
        currencyCode: 'RUB',
    },
    RW: {
        name: 'Rwanda',
        alpha2: 'RW',
        alpha3: 'RWA',
        subregion: 'Eastern Africa',
        currencyCode: 'RWF',
    },
    BL: {
        name: 'Saint Barthélemy',
        alpha2: 'BL',
        alpha3: 'BLM',
        subregion: 'Caribbean',
        currencyCode: 'EUR',
    },
    SH: {
        name: 'Saint Helena, Ascension and Tristan da Cunha',
        alpha2: 'SH',
        alpha3: 'SHN',
        subregion: 'Western Africa',
        currencyCode: 'GBP',
    },
    KN: {
        name: 'Saint Kitts and Nevis',
        alpha2: 'KN',
        alpha3: 'KNA',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    LC: {
        name: 'Saint Lucia',
        alpha2: 'LC',
        alpha3: 'LCA',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    MF: {
        name: 'Saint Martin (French part)',
        alpha2: 'MF',
        alpha3: 'MAF',
        subregion: 'Caribbean',
        currencyCode: 'ANG',
    },
    PM: {
        name: 'Saint Pierre and Miquelon',
        alpha2: 'PM',
        alpha3: 'SPM',
        subregion: 'Northern America',
        currencyCode: 'EUR',
    },
    VC: {
        name: 'Saint Vincent and the Grenadines',
        alpha2: 'VC',
        alpha3: 'VCT',
        subregion: 'Caribbean',
        currencyCode: 'XCD',
    },
    WS: {
        name: 'Samoa',
        alpha2: 'WS',
        alpha3: 'WSM',
        subregion: 'Polynesia',
        currencyCode: 'WST',
    },
    SM: {
        name: 'San Marino',
        alpha2: 'SM',
        alpha3: 'SMR',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    ST: {
        name: 'Sao Tome and Principe',
        alpha2: 'ST',
        alpha3: 'STP',
        subregion: 'Middle Africa',
        currencyCode: 'STD',
    },
    SA: {
        name: 'Saudi Arabia',
        alpha2: 'SA',
        alpha3: 'SAU',
        subregion: 'Western Asia',
        currencyCode: 'SAR',
    },
    SN: {
        name: 'Senegal',
        alpha2: 'SN',
        alpha3: 'SEN',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    RS: {
        name: 'Serbia',
        alpha2: 'RS',
        alpha3: 'SRB',
        subregion: 'Southern Europe',
        currencyCode: 'RSD',
    },
    SC: {
        name: 'Seychelles',
        alpha2: 'SC',
        alpha3: 'SYC',
        subregion: 'Eastern Africa',
        currencyCode: 'SCR',
    },
    SL: {
        name: 'Sierra Leone',
        alpha2: 'SL',
        alpha3: 'SLE',
        subregion: 'Western Africa',
        currencyCode: 'SLL',
    },
    SG: {
        name: 'Singapore',
        alpha2: 'SG',
        alpha3: 'SGP',
        subregion: 'South-Eastern Asia',
        currencyCode: 'SGD',
    },
    SX: {
        name: 'Sint Maarten (Dutch part)',
        alpha2: 'SX',
        alpha3: 'SXM',
        subregion: 'Caribbean',
        currencyCode: 'ANG',
    },
    SK: {
        name: 'Slovakia',
        alpha2: 'SK',
        alpha3: 'SVK',
        subregion: 'Eastern Europe',
        currencyCode: 'EUR',
    },
    SI: {
        name: 'Slovenia',
        alpha2: 'SI',
        alpha3: 'SVN',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    SB: {
        name: 'Solomon Islands',
        alpha2: 'SB',
        alpha3: 'SLB',
        subregion: 'Melanesia',
        currencyCode: 'SBD',
    },
    SO: {
        name: 'Somalia',
        alpha2: 'SO',
        alpha3: 'SOM',
        subregion: 'Eastern Africa',
        currencyCode: 'SOS',
    },
    ZA: {
        name: 'South Africa',
        alpha2: 'ZA',
        alpha3: 'ZAF',
        subregion: 'Southern Africa',
        currencyCode: 'ZAR',
    },
    GS: {
        name: 'South Georgia and the South Sandwich Islands',
        alpha2: 'GS',
        alpha3: 'SGS',
        subregion: 'South America',
        currencyCode: 'GBP',
    },
    SS: {
        name: 'South Sudan',
        alpha2: 'SS',
        alpha3: 'SSD',
        subregion: 'Middle Africa',
        currencyCode: 'SSP',
    },
    ES: {
        name: 'Spain',
        alpha2: 'ES',
        alpha3: 'ESP',
        subregion: 'Southern Europe',
        currencyCode: 'EUR',
    },
    LK: {
        name: 'Sri Lanka',
        alpha2: 'LK',
        alpha3: 'LKA',
        subregion: 'Southern Asia',
        currencyCode: 'LKR',
    },
    SD: {
        name: 'Sudan',
        alpha2: 'SD',
        alpha3: 'SDN',
        subregion: 'Northern Africa',
        currencyCode: 'SDG',
    },
    SR: {
        name: 'Suriname',
        alpha2: 'SR',
        alpha3: 'SUR',
        subregion: 'South America',
        currencyCode: 'SRD',
    },
    SJ: {
        name: 'Svalbard and Jan Mayen',
        alpha2: 'SJ',
        alpha3: 'SJM',
        subregion: 'Northern Europe',
        currencyCode: 'NOK',
    },
    SE: {
        name: 'Sweden',
        alpha2: 'SE',
        alpha3: 'SWE',
        subregion: 'Northern Europe',
        currencyCode: 'SEK',
    },
    CH: {
        name: 'Switzerland',
        alpha2: 'CH',
        alpha3: 'CHE',
        subregion: 'Western Europe',
        currencyCode: 'CHF',
    },
    SY: {
        name: 'Syrian Arab Republic',
        alpha2: 'SY',
        alpha3: 'SYR',
        subregion: 'Western Asia',
        currencyCode: 'SYP',
    },
    TW: {
        name: 'Taiwan, Province of China',
        alpha2: 'TW',
        alpha3: 'TWN',
        subregion: 'Eastern Asia',
        currencyCode: 'TWD',
    },
    TJ: {
        name: 'Tajikistan',
        alpha2: 'TJ',
        alpha3: 'TJK',
        subregion: 'Central Asia',
        currencyCode: 'TJS',
    },
    TZ: {
        name: 'Tanzania, United Republic of',
        alpha2: 'TZ',
        alpha3: 'TZA',
        subregion: 'Eastern Africa',
        currencyCode: 'TZS',
    },
    TH: {
        name: 'Thailand',
        alpha2: 'TH',
        alpha3: 'THA',
        subregion: 'South-Eastern Asia',
        currencyCode: 'THB',
    },
    TL: {
        name: 'Timor-Leste',
        alpha2: 'TL',
        alpha3: 'TLS',
        subregion: 'South-Eastern Asia',
        currencyCode: 'USD',
    },
    TG: {
        name: 'Togo',
        alpha2: 'TG',
        alpha3: 'TGO',
        subregion: 'Western Africa',
        currencyCode: 'XOF',
    },
    TK: {
        name: 'Tokelau',
        alpha2: 'TK',
        alpha3: 'TKL',
        subregion: 'Polynesia',
        currencyCode: 'NZD',
    },
    TO: {
        name: 'Tonga',
        alpha2: 'TO',
        alpha3: 'TON',
        subregion: 'Polynesia',
        currencyCode: 'TOP',
    },
    TT: {
        name: 'Trinidad and Tobago',
        alpha2: 'TT',
        alpha3: 'TTO',
        subregion: 'Caribbean',
        currencyCode: 'TTD',
    },
    TN: {
        name: 'Tunisia',
        alpha2: 'TN',
        alpha3: 'TUN',
        subregion: 'Northern Africa',
        currencyCode: 'TND',
    },
    TR: {
        name: 'Turkey',
        alpha2: 'TR',
        alpha3: 'TUR',
        subregion: 'Western Asia',
        currencyCode: 'TRY',
    },
    TM: {
        name: 'Turkmenistan',
        alpha2: 'TM',
        alpha3: 'TKM',
        subregion: 'Central Asia',
        currencyCode: 'TMT',
    },
    TC: {
        name: 'Turks and Caicos Islands',
        alpha2: 'TC',
        alpha3: 'TCA',
        subregion: 'Caribbean',
        currencyCode: 'USD',
    },
    TV: {
        name: 'Tuvalu',
        alpha2: 'TV',
        alpha3: 'TUV',
        subregion: 'Polynesia',
        currencyCode: 'AUD',
    },
    UG: {
        name: 'Uganda',
        alpha2: 'UG',
        alpha3: 'UGA',
        subregion: 'Eastern Africa',
        currencyCode: 'UGX',
    },
    UA: {
        name: 'Ukraine',
        alpha2: 'UA',
        alpha3: 'UKR',
        subregion: 'Eastern Europe',
        currencyCode: 'UAH',
    },
    AE: {
        name: 'United Arab Emirates',
        alpha2: 'AE',
        alpha3: 'ARE',
        subregion: 'Western Asia',
        currencyCode: 'AED',
    },
    GB: {
        name: 'United Kingdom (UK)',
        alpha2: 'GB',
        alpha3: 'GBR',
        subregion: 'Northern Europe',
        currencyCode: 'GBP',
    },
    US: {
        name: 'USA',
        alpha2: 'US',
        alpha3: 'USA',
        subregion: 'Northern America',
        currencyCode: 'USD',
    },
    UM: {
        name: 'United States Minor Outlying Islands',
        alpha2: 'UM',
        alpha3: 'UMI',
        subregion: 'Northern America',
        currencyCode: 'USD',
    },
    UY: {
        name: 'Uruguay',
        alpha2: 'UY',
        alpha3: 'URY',
        subregion: 'South America',
        currencyCode: 'UYU',
    },
    UZ: {
        name: 'Uzbekistan',
        alpha2: 'UZ',
        alpha3: 'UZB',
        subregion: 'Central Asia',
        currencyCode: 'UZS',
    },
    VU: {
        name: 'Vanuatu',
        alpha2: 'VU',
        alpha3: 'VUT',
        subregion: 'Melanesia',
        currencyCode: 'VUV',
    },
    VE: {
        name: 'Venezuela (Bolivarian Republic of)',
        alpha2: 'VE',
        alpha3: 'VEN',
        subregion: 'South America',
        currencyCode: 'VEF',
    },
    VN: {
        name: 'Viet Nam',
        alpha2: 'VN',
        alpha3: 'VNM',
        subregion: 'South-Eastern Asia',
        currencyCode: 'VND',
    },
    VG: {
        name: 'Virgin Islands (British)',
        alpha2: 'VG',
        alpha3: 'VGB',
        subregion: 'Caribbean',
        currencyCode: 'USD',
    },
    VI: {
        name: 'Virgin Islands (U.S.)',
        alpha2: 'VI',
        alpha3: 'VIR',
        subregion: 'Caribbean',
        currencyCode: 'USD',
    },
    WF: {
        name: 'Wallis and Futuna',
        alpha2: 'WF',
        alpha3: 'WLF',
        subregion: 'Polynesia',
        currencyCode: 'XPF',
    },
    EH: {
        name: 'Western Sahara',
        alpha2: 'EH',
        alpha3: 'ESH',
        subregion: 'Northern Africa',
        currencyCode: 'MAD',
    },
    YE: {
        name: 'Yemen',
        alpha2: 'YE',
        alpha3: 'YEM',
        subregion: 'Western Asia',
        currencyCode: 'YER',
    },
    ZM: {
        name: 'Zambia',
        alpha2: 'ZM',
        alpha3: 'ZMB',
        subregion: 'Eastern Africa',
        currencyCode: 'ZMW',
    },
    ZW: {
        name: 'Zimbabwe',
        alpha2: 'ZW',
        alpha3: 'ZWE',
        subregion: 'Eastern Africa',
        currencyCode: 'USD',
    },
};

export const countries: Record<string, Country> = Object.assign(
    {
        UK: {
            name: 'United Kingdom (UK)',
            alpha2: 'GB',
            alpha3: 'GBR',
            subregion: 'Northern Europe',
            currencyCode: 'GBP',
        },
    },
    countriesWithUnduplicatedCodes
);

export const countriesByName = Object.values(countries).reduce((acc, curr, index) => {
    acc[curr.name] = {
        ...curr,
        id: index,
    };
    return acc;
}, {} as Record<string, CountryByName>);

export const countryGroups = [
    'Northern Europe',
    'Southern Europe',
    'Eastern Europe',
    'Western Europe',
    'Northern America',
    'Central America',
    'South America',
    'Caribbean',
    'Northern Africa',
    'Southern Africa',
    'Middle Africa',
    'Eastern Africa',
    'Western Africa',
    'Central Asia',
    'Southern Asia',
    'South-Eastern Asia',
    'Eastern Asia',
    'Western Asia',
    'Australia and New Zealand',
    'Polynesia',
    'Melanesia',
    'Micronesia',
    'Other',
];

export const CountryField = ({
    tooltipText,
    fieldProps,
}: {
    tooltipText?: string;
    fieldProps?: Partial<AppDropdownSelectFieldProps>;
}) => {
    const [inputText, setInputText] = useState('');
    const countryArr = useMemo(() => Object.values(countries), []);

    const groups: FilterGroup[] = useMemo(() => {
        const countriesGrouped = countryGroups.reduce((acc, group) => {
            acc[group] = [];
            return acc;
        }, {} as Record<string, Array<Country & { id: string }>>);

        const countriesFiltered = inputText
            ? countryArr.filter((c) =>
                  [c.name, c.alpha2, c.alpha3, c.subregion]
                      .map((s) => s.toLowerCase())
                      .some((str) => str.includes(inputText.toLowerCase()))
              )
            : countryArr;

        countriesFiltered.forEach((c) => {
            countriesGrouped[c.subregion].push({ id: c.alpha2, ...c });
        });

        Object.keys(countriesGrouped).forEach((key) => {
            countriesGrouped[key] = countriesGrouped[key].sort((a, b) =>
                a.subregion === 'Other' ? 1 : b.subregion === 'Other' ? -1 : -a.subregion.localeCompare(b.subregion)
            );
        });

        return Object.keys(countriesGrouped).map((key) => ({ name: key, items: countriesGrouped[key] }));
    }, [countryArr, inputText]);

    return (
        <AppDropdownSelectField
            inputText={inputText}
            setInputText={setInputText}
            required
            name="country"
            label="Country"
            groups={groups}
            tooltipText={tooltipText}
            {...fieldProps}
        />
    );
};
